apiVersion: v1
kind: ConfigMap

metadata:
  name: otel-collector-config

data:
  config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

          http:
            endpoint: 0.0.0.0:4318

      kubeletstats:
        collection_interval: 30s
        auth_type: serviceAccount
        endpoint: https://${env:K8S_NODE_NAME}:10250
        insecure_skip_verify: true

      k8s_cluster:
        collection_interval: 30s

      prometheus:
        config:
          scrape_configs:
            - job_name: kube-state-metrics

              scrape_interval: 30s

              static_configs:
                - targets:
                    - kube-state-metrics.kube-system.svc.cluster.local:8080

    processors:
      resource:
        attributes:
          - key: k8s.cluster.name
            value: otel-labs
            action: upsert

          - key: deployment.environment
            value: lab
            action: upsert

      k8sattributes:

      batch:

    exporters:
      debug:
        verbosity: detailed

      otlphttp/newrelic:
        endpoint: https://otlp.eu01.nr-data.net

        headers:
          api-key: ${env:NEW_RELIC_LICENSE_KEY}

      otlphttp/honeycomb:
        endpoint: https://api.honeycomb.io

        headers:
          x-honeycomb-team: ${env:HONEYCOMB_API_KEY}

    service:
      extensions:
        - health_check

      telemetry:
        logs:
          level: info

      pipelines:
        traces:
          receivers:
            - otlp

          processors:
            - resource
            - k8sattributes
            - batch

          exporters:
            - debug
            - otlphttp/newrelic
            - otlphttp/honeycomb

        metrics:
          receivers:
            - otlp
            - kubeletstats
            - k8s_cluster
            - prometheus

          processors:
            - resource
            - k8sattributes
            - batch

          exporters:
            - debug
            - otlphttp/newrelic
            - otlphttp/honeycomb

        logs:
          receivers:
            - otlp

          processors:
            - resource
            - k8sattributes
            - batch

          exporters:
            - debug
            - otlphttp/newrelic
            - otlphttp/honeycomb