apiVersion: apps/v1
kind: Deployment

metadata:
  name: otel-collector

spec:
  replicas: 1

  selector:
    matchLabels:
      app: otel-collector

  template:
    metadata:
      labels:
        app: otel-collector

    spec:
      serviceAccountName: otel-collector

      containers:
        - name: otel-collector

          image: otel/opentelemetry-collector-contrib:0.131.0

          args:
            - "--config=/etc/otelcol-contrib/config.yaml"

          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic-secret
                  key: NEW_RELIC_LICENSE_KEY

            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic-secret
                  key: HONEYCOMB_API_KEY

          ports:
            - name: grpc
              containerPort: 4317

            - name: http
              containerPort: 4318

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /
              port: 13133

          readinessProbe:
            httpGet:
              path: /
              port: 13133

          volumeMounts:
            - name: collector-config
              mountPath: /etc/otelcol-contrib/config.yaml
              subPath: config.yaml

      volumes:
        - name: collector-config
          configMap:
            name: otel-collector-config