  #create a file as secrets.yaml with these vaules.

apiVersion: v1
kind: Secret
metadata:
  name: newrelic-secret
  namespace: otel-labs
type: Opaque
stringData:
  NEW_RELIC_LICENSE_KEY: <your_new_relic_license_key_here>
  HONEYCOMB_API_KEY: <your_honeycomb_api_key_here>