apiVersion: v1
kind: Secret
metadata:
  name: otel-backend-secret
  namespace: otel-labs
type: Opaque
stringData:
  NEW_RELIC_LICENSE_KEY: eu01xe126068cdc95eadfd9020e3ee23d877NRAL
  HONEYCOMB_API_KEY: hcaik_01kvcbevd1v996cxg3pcf8zfgmq0rxqdz5ztt1h3d2p57ejwjp3rdrgkrn