apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: falco-exception
  namespace: argocd
spec:
  exceptions:
    - policyName: pod-security-baseline
      ruleNames:
        - autogen-disallow-privilege-escalation
        - autogen-require-drop-all-capabilities
        - autogen-require-read-only-root-filesystem
        - autogen-require-run-as-non-root
        - autogen-require-runtime-default-seccomp

    - policyName: resource-security
      ruleNames:
        - autogen-require-resource-limits
        - autogen-require-resource-requests

  match:
    any:
      # Falco DaemonSet
      - resources:
          kinds:
            - DaemonSet
          namespaces:
            - falco
          names:
            - falco

      # Falco Sidekick Deployment
      - resources:
          kinds:
            - Deployment
          namespaces:
            - falco
          names:
            - falco-falcosidekick