apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: falco-exception
  namespace: argocd
spec:
  exceptions:
    - policyName: pod-security-baseline
      ruleNames:
        - disallow-privilege-escalation
        - require-drop-all-capabilities
        - require-read-only-root-filesystem
        - require-run-as-non-root
        - require-runtime-default-seccomp

    - policyName: resource-security
      ruleNames:
        - require-resource-limits
        - require-resource-requests

  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - falco
          names:
            - falco-*