apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pod-security-policy.yml
  # - ns-policy.yml
  - tag-policy.yml
  - resource-policy.yml
  - trusted-registry-policy.yml
  - traefik-pod-exception-policy.yml