apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: namespace-security

spec:
  background: true

  rules:
    - name: disallow-default-namespace
      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        message: Deploying workloads to the default namespace is not allowed.
        deny:
          conditions:
            any:
              - key: "{{ request.namespace }}"
                operator: Equals
                value: default

  validationFailureAction: Enforce