apiVersion: kyverno.io/v2
kind: PolicyException

metadata:
  name: traefik-resource-exception
  namespace: argocd

spec:
  exceptions:
    - policyName: resource-security
      ruleNames:
        - require-resource-requests
        - require-resource-limits
        - autogen-require-resource-requests
        - autogen-require-resource-limits

    - policyName: trusted-image-registries #must match the metadata.name in the trsuted registry policy
      ruleNames:
        - validate-image-registry
        - autogen-validate-image-registry

  match:
    any:
      - resources:
          kinds:
            - Deployment
            - Pod
          namespaces:
            - traefik
          names:
            - traefik
            - traefik-*