apiVersion: apps/v1
kind: Deployment

metadata:
  name: falco-trigger
  namespace: falco
  labels:
    app: falco-trigger
    purpose: falco-validation
    component: security-testing
    lifecycle: archived

spec:
  replicas: 1

  selector:
    matchLabels:
      app: falco-trigger

  template:
    metadata:
      labels:
        app: falco-trigger
        purpose: falco-validation
        component: security-testing
        lifecycle: archived

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: falco-trigger
          image: ghcr.io/sagarkpanda/alpine:3.22

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi

          command:
            - /bin/sh
            - -c
            - |
              whoami
              while true; do
                sleep 3600
              done