apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kube-state-metrics
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-state-metrics
    targetRevision: 6.1.0

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true