# ArgoCD Application that deploys the Traefik Ingress Controller using the official Helm chart.

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: traefik
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 40.3.0

    helm:
      values: |
        ingressClass:
          enabled: true
          isDefaultClass: true

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true