name: Gitleaks

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - '.github/workflows/trivy.yml'
  pull_request:

permissions:
  contents: read
  security-events: write

env:
  DD_BUILD_ID: ${{ github.run_number }}
  DD_BRANCH: ${{ github.ref_name }}
  DD_COMMIT: ${{ github.sha }}

  DD_PRODUCT_TYPE: SP Org
  DD_PRODUCT: Otel Labs
  DD_ENGAGEMENT: Platform Sec Engagement
  DD_ENVIRONMENT: Lab

jobs:
  gitleaks:
    name: Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_ENABLE_COMMENTS: false
          GITLEAKS_ENABLE_UPLOAD_RESULTS: true

      - name: Generate SARIF
        run: |
          docker run --rm \
            -v "$PWD:/path" \
            ghcr.io/gitleaks/gitleaks:latest detect \
            --source=/path \
            --report-format sarif \
            --report-path /path/gitleaks.sarif \
            --exit-code 0

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      - name: Upload Gitleaks Results to DefectDojo
        if: always()
        run: |
          curl -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Accept: application/json" \
            -F "scan_type=SARIF" \
            -F "file=@gitleaks.sarif" \
            -F "auto_create_context=true" \
            -F "product_type_name=$DD_PRODUCT_TYPE" \
            -F "product_name=$DD_PRODUCT" \
            -F "engagement_name=$DD_ENGAGEMENT" \
            -F "test_title=Gitleaks" \
            -F "close_old_findings=true" \
            -F "do_not_reactivate=false" \
            -F "environment=$DD_ENVIRONMENT" \
            -F "build_id=$DD_BUILD_ID" \
            -F "branch_tag=$DD_BRANCH" \
            -F "commit_hash=$DD_COMMIT" \
            -F "tags=github-actions,gitleaks,platform,$DD_BRANCH"