name: Gitleaks

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - '.github/workflows/trivy.yml'
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_ENABLE_COMMENTS: false
          GITLEAKS_ENABLE_UPLOAD_RESULTS: true

      - name: Generate SARIF
        run: |
          docker run --rm \
            -v "$PWD:/path" \
            ghcr.io/gitleaks/gitleaks:latest detect \
            --source=/path \
            --report-format sarif \
            --report-path /path/gitleaks.sarif \
            --exit-code 0

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      # - name: Upload Gitleaks Results to DefectDojo
      #   if: always()
      #   run: |
      #     curl -X POST \
      #       "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
      #       -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
      #       -H "Accept: application/json" \
      #       -F "scan_type=SARIF" \
      #       -F "file=@gitleaks.sarif" \
      #       -F "auto_create_context=true" \
      #       -F "product_type_name=SP Org" \
      #       -F "product_name=Otel Labs" \
      #       -F "engagement_name=Platform Sec Engagement" \
      #       -F "test_title=Gitleaks" \
      #       -F "close_old_findings=true" \
      #       -F "do_not_reactivate=false" \
      #       -F "environment=Lab" \
      #       -F "build_id=${{ github.run_number }}" \
      #       -F "branch_tag=${{ github.ref_name }}" \
      #       -F "commit_hash=${{ github.sha }}" \
      #       -F "tags=github-actions,gitleaks,platform,${{ github.ref_name }}"