name: Trivy Config Scan

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
    paths-ignore:
      - "README.md"
      - '.github/workflows/gitleaks.yml'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy-k8s:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      # - name: Scan Kubernetes manifests
      #   uses: aquasecurity/trivy-action@v0.36.0
      #   with:
      #     scan-type: config
      #     scan-ref: ./k8s
      #     format: sarif
      #     output: trivy-k8s.sarif
      #     severity: HIGH,CRITICAL
      #     exit-code: 0

      - name: Scan Kubernetes manifests
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: ./k8s
          trivy-config: .trivy/config.yaml
          format: sarif
          output: trivy-k8s.sarif
          severity: HIGH,CRITICAL
          exit-code: 0

      - name: Upload Kubernetes SARIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-k8s-sarif
          path: trivy-k8s.sarif

      - name: Upload Kubernetes SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-k8s.sarif
          category: trivy-k8s

      # - name: Upload Trivy Kubernetes Results to DefectDojo
      #   if: always()
      #   run: |
      #     curl -X POST \
      #       "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
      #       -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
      #       -H "Accept: application/json" \
      #       -F "scan_type=SARIF" \
      #       -F "file=@trivy-k8s.sarif" \
      #       -F "auto_create_context=true" \
      #       -F "product_type_name=SP Org" \
      #       -F "product_name=Otel Labs" \
      #       -F "engagement_name=Platform Sec Engagement" \
      #       -F "test_title=Trivy Kubernetes" \
      #       -F "close_old_findings=true" \
      #       -F "do_not_reactivate=false" \
      #       -F "environment=Lab" \
      #       -F "build_id=${{ github.run_number }}" \
      #       -F "branch_tag=${{ github.ref_name }}" \
      #       -F "commit_hash=${{ github.sha }}" \
      #       -F "tags=github-actions,trivy,kubernetes,platform,${{ github.ref_name }}"

  trivy-terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Scan Terraform
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: ./terraform
          format: sarif
          output: trivy-terraform.sarif
          severity: HIGH,CRITICAL
          exit-code: 0

      - name: Upload Terraform SARIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-terraform-sarif
          path: trivy-terraform.sarif

      - name: Upload Terraform SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-terraform.sarif
          category: trivy-terraform

      # - name: Upload Trivy Terraform Results to DefectDojo
      #   if: always()
      #   run: |
      #     curl -X POST \
      #       "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
      #       -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
      #       -H "Accept: application/json" \
      #       -F "scan_type=SARIF" \
      #       -F "file=@trivy-terraform.sarif" \
      #       -F "auto_create_context=true" \
      #       -F "product_type_name=SP Org" \
      #       -F "product_name=Otel Labs" \
      #       -F "engagement_name=Platform Sec Engagement" \
      #       -F "test_title=Trivy Terraform" \
      #       -F "close_old_findings=true" \
      #       -F "do_not_reactivate=false" \
      #       -F "environment=Lab" \
      #       -F "build_id=${{ github.run_number }}" \
      #       -F "branch_tag=${{ github.ref_name }}" \
      #       -F "commit_hash=${{ github.sha }}" \
      #       -F "tags=github-actions,trivy,terraform,platform,${{ github.ref_name }}"
