name: OWASP ZAP DAST

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  DAST_TARGET_URL: http://otel.sagarpanda.com

  DD_PRODUCT_TYPE: SP Org
  DD_PRODUCT: Otel Labs
  DD_ENGAGEMENT: App Security Engagement
  DD_ENVIRONMENT: Lab
  DD_BUILD_ID: ${{ github.run_number }}
  DD_BRANCH: ${{ github.ref_name }}
  DD_COMMIT: ${{ github.sha }}

permissions:
  contents: read
  issues: write

jobs:
  zap:
    name: ZAP Full Scan
    if: github.event.head_commit.committer.username == 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check application availability
        id: check_url
        run: |
          echo "Checking ${DAST_TARGET_URL}"

          if curl \
            --fail \
            --silent \
            --show-error \
            --location \
            --max-time 30 \
            "${DAST_TARGET_URL}" > /dev/null; then

            echo "reachable=true" >> "$GITHUB_OUTPUT"
            echo "Application is reachable."
          else
            echo "reachable=false" >> "$GITHUB_OUTPUT"
            echo "Application is not reachable. Skipping ZAP."
          fi

      - name: Run OWASP ZAP Full Scan
        if: steps.check_url.outputs.reachable == 'true'
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: ${{ env.DAST_TARGET_URL }}
          # token: ${{ secrets.GITHUB_TOKEN }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-I -x report_xml.xml'
          # allow_issue_writing: true
          # issue_title: OWASP ZAP DAST Results
          artifact_name: 'zap-dast-report'
          fail_action: false

      - name: Upload ZAP Results to DefectDojo
        if: steps.check_url.outputs.reachable == 'true'
        run: |
          curl -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "Accept: application/json" \
            -F "scan_type=ZAP Scan" \
            -F "file=@report_xml.xml" \
            -F "auto_create_context=true" \
            -F "product_type_name=$DD_PRODUCT_TYPE" \
            -F "product_name=$DD_PRODUCT" \
            -F "engagement_name=$DD_ENGAGEMENT" \
            -F "test_title=OWASP ZAP DAST" \
            -F "close_old_findings=true" \
            -F "do_not_reactivate=false" \
            -F "environment=$DD_ENVIRONMENT" \
            -F "build_id=$DD_BUILD_ID" \
            -F "branch_tag=$DD_BRANCH" \
            -F "commit_hash=$DD_COMMIT" \
            -F "tags=github-actions,zap,dast,$DD_BRANCH"
